name: dctkit
channels:
  - conda-forge
  - defaults
dependencies:
  - gmsh=4.11.1
  - hyperfine
  - jax
  - jaxopt
  - numpy=1.24.2
  - pygmo=2.19.5
  - petsc4py
  - python
  - python-gmsh
  - scipy=1.10.0
  - typeguard
  - yaml=0.2.5
  - jupyterlab
  - trame
  - ipywidgets
  - pyvista
  - pip
  - pip:
    - pygmsh